; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32 @6.5.0
board = esp32s3_flash_16MB
framework = arduino
monitor_speed = 115200 ;Serial Baud Rate Setting

; debug_tool = esp-builtin
; upload_protocol = esp-builtin
upload_speed = 921600 ; 460800, 512000, 460800, 256000, 115200
board_upload.flash_size = 16MB 

board_build.arduino.memory_type = qio_opi ;Enable internal PSRAM
; board_build.memory_type = qio_qspi ;Enable external PSRAM

board_build.partitions = default_16MB.csv 

build_flags = 
    -Wall ;all errors that everybody could agree on
    -Wextra ;somebody agree on
    ; -Werror ;Think of "Warning" as "Error".
    -D CORE_DEBUG_LEVEL=1 ;Debug level 0-5
    -D BOARD_HAS_PSRAM ;Enable external PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 ;1 is to use the USB port as a serial port
    -D ARDUINO_RUNNING_CORE=1       ; Arduino Runs On Core (setup, loop)
    -D ARDUINO_EVENT_RUNNING_CORE=1 ; Events Run On Core

[platformio]
boards_dir = ./boards
lib_dir = ./libraries

; src_dir = examples/${platformio.default_envs}
; default_envs = DMIC_ReadData
; default_envs = Wifi_Music
; default_envs = APA102_Blink
; default_envs = Voice_Speaker
; default_envs = Voice_Speaker_APA102
; default_envs = GFX
; default_envs = GFX_CST816D_Image
; default_envs = CST816D
; default_envs = Original_Test
; default_envs = GFX_Wifi_AP_Contract
; default_envs = GFX_Wifi_STA_Contract
; default_envs = IIC_Scan_2
; default_envs = Animated_Eyes_1
; default_envs = TFT

src_dir = debug/examples/${platformio.default_envs}
default_envs = ChipScan
; default_envs = SD
; default_envs = SD_DMIC
; default_envs = IO
default_envs = GC9D01N
; default_envs = Rotary_Encoder
; default_envs = Deep_Sleep_Wake_Up
; default_envs = High_Intensity_Test
; default_envs = Wifi_AP_Contract
; default_envs = Wifi_STA_Contract
; default_envs = WIFI_HTTP_Download_File
; default_envs = FFat_Test
; default_envs = Music_Loop

[env:DMIC_ReadData]
[env:Wifi_Music]
[env:APA102_Blink]
[env:Voice_Speaker]
[env:Voice_Speaker_APA102]
[env:GFX]
[env:GFX_CST816D_Image]
[env:CST816D]
[env:Original_Test]
[env:GFX_Wifi_AP_Contract]
[env:GFX_Wifi_STA_Contract]
[env:IIC_Scan_2]
[env:Animated_Eyes_1]
[env:TFT]

[env:ChipScan]
[env:SD]
[env:SD_DMIC]
[env:IO]
[env:GC9D01N]
[env:Rotary_Encoder]
[env:Deep_Sleep_Wake_Up]
[env:High_Intensity_Test]
[env:Wifi_AP_Contract]
[env:Wifi_STA_Contract]
[env:WIFI_HTTP_Download_File]
[env:FFat_Test]
[env:Music_Loop]




